### ISSUE TITLE
Travis build failing

### ISSUE THREAD

**Issue by craigmdennis** [docpad/docpad-plugin-pug#2]
@balupton Everything works as expected but the Travis build is failing. I'm not sure what the issue is but happy to fix it if you can point me in the right direction.

**Comment by balupton** [comment]
Seems all the docpad plugins are having the same issue. Do the npm release regardless. And I'll sort out the travis for all the plugins issue after my current batch of work.

**Comment by balupton** [comment]
@craigmdennis so the issue was due to the conventions not working for npm v3

I've released https://github.com/bevry/based which when run, will update the plugin conventions to the latest. However it requires secret tokens for use in the initial travis setup. As such, for now, I need to run it for each plugin. Will do it now for pug.

**Comment by balupton** [comment]
@craigmdennis okay, updated - from now on, to do a release, all you have to do is do the package.json version bump and the HISTORY.md entry, commit, and then run `npm run our:release` -  full instructions in `CONTRIBUTING.md`
